# Generated by Django 6.0.3 on 2026-03-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('summary', models.TextField(verbose_name='Аннотация')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выхода')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('age_limit', models.PositiveIntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Возрастное ограничение')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre', verbose_name='Жанры')),
            ],
        ),
    ]
